import { Link, useRouterState } from "@tanstack/react-router";
import { Activity, ChartBar as BarChart3, Bot, Gauge, History, ChartLine as LineChart, Palette, Radio, Wallet, Zap, MoveHorizontal as MoreHorizontal, BookOpen, Key, Rocket, MessageSquare, Shield, TrendingUp, Bell, Flame, Inbox, Server, Cpu, Wrench, Brain, Sparkles, Infinity as InfinityIcon, DollarSign, Eye, Twitter, Calendar as CalIcon, Calculator, Maximize, Minimize, Globe, LifeBuoy, SquareSplitHorizontal as SplitSquareHorizontal, TextAlignJustify as AlignJustify, ArrowUpFromLine, Landmark, ListChecks, Coins, Dices, Percent, ChevronDown, ChevronRight, LayoutDashboard, Settings, Timer, Layers, Target, Crosshair, PanelLeftClose, PanelLeftOpen, Menu, X, Play, SquareCheck as CheckSquare, TrendingDown, ChartCandlestick as CandlestickChart, Music, AudioWaveform as WaveIcon } from "lucide-react";
import { useEffect, useState, type ReactNode } from "react";
import { THEMES, useTheme } from "@/hooks/use-theme";
import { ThreeBackground } from "./ThreeBackground";
import { useIsMobile } from "@/hooks/use-mobile";

const NAV = [
  { to: "/", label: "Dashboard", icon: Gauge },
  { to: "/ultra", label: "Ultra", icon: Sparkles },
  { to: "/smc", label: "SMC", icon: Layers },
  { to: "/persistence", label: "24/7", icon: InfinityIcon },
  { to: "/scanner", label: "Scanner", icon: Radio },
  { to: "/signals", label: "Signals", icon: Zap },
  { to: "/mtf", label: "MTF Analyzer", icon: Layers },
  { to: "/alert-builder", label: "Alert Builder", icon: Bell },
  { to: "/signal-stats", label: "Signal Stats", icon: BarChart3 },
  { to: "/local-ai", label: "Local AI", icon: Brain },
  { to: "/options-flow", label: "Options", icon: DollarSign },
  { to: "/dark-pool", label: "Dark Pool", icon: Eye },
  { to: "/sentiment", label: "Sentiment", icon: Twitter },
  { to: "/neural", label: "Neural Net", icon: Brain },
  { to: "/market-profile", label: "Market Profile", icon: BarChart3 },
  { to: "/analysis", label: "Analysis", icon: Activity },
  { to: "/advanced-analysis", label: "Advanced Analysis", icon: Sparkles },
  { to: "/tools", label: "Tools", icon: Wrench },
  { to: "/currency-strength", label: "Strength", icon: Gauge },
  { to: "/sessions", label: "Sessions", icon: Globe },
  { to: "/plan", label: "Trading Plan", icon: ListChecks },
  { to: "/simulator", label: "Simulator", icon: Dices },
  { to: "/options-calc", label: "Black-Scholes", icon: Percent },
  { to: "/pip-value", label: "Pip Value", icon: Coins },
  { to: "/compound", label: "Growth Calc", icon: TrendingUp },
  { to: "/recovery", label: "Recovery", icon: LifeBuoy },
  { to: "/scaling", label: "Scale Out", icon: SplitSquareHorizontal },
  { to: "/risk-calculator", label: "Risk Calc", icon: Calculator },
  { to: "/pivot", label: "Pivots", icon: ArrowUpFromLine },
  { to: "/fibonacci", label: "Fibonacci", icon: AlignJustify },
  { to: "/margin", label: "Margin", icon: Landmark },
  { to: "/journal", label: "Journal", icon: BookOpen },
  { to: "/calendar", label: "Calendar", icon: CalIcon },
  { to: "/chat", label: "AI Chat", icon: MessageSquare },
  { to: "/chart", label: "Chart", icon: LineChart },
  { to: "/heatmap", label: "Heatmap", icon: Flame },
  { to: "/backtest", label: "Backtest", icon: History },
  { to: "/optimizer", label: "Optimizer", icon: Wrench },
  { to: "/confluence", label: "Confluence", icon: Crosshair },
  { to: "/automation", label: "Automation", icon: Timer },
  { to: "/bot", label: "Auto-Bot", icon: Rocket },
  { to: "/zo", label: "Zo Cloud", icon: Cpu },
  { to: "/pnl", label: "PnL", icon: TrendingUp },
  { to: "/alerts", label: "Alerts", icon: Bell },
  { to: "/dlq", label: "DLQ Admin", icon: Inbox },
  { to: "/system", label: "System", icon: Cpu },
  { to: "/deriv", label: "Deriv API", icon: Wallet },
  { to: "/telegram", label: "Telegram", icon: Bot },
  { to: "/api-keys", label: "API Keys", icon: Key },
  { to: "/webhook-events", label: "Webhooks", icon: Shield },
  { to: "/docs", label: "API Docs", icon: BookOpen },
  { to: "/monte-carlo", label: "Monte Carlo", icon: Dices },
  { to: "/correlation", label: "Correlation", icon: Activity },
  { to: "/volatility", label: "Vol Regime", icon: Flame },
  { to: "/streak", label: "Streak Tracker", icon: Flame },
  { to: "/session-overlap", label: "Session Overlap", icon: Globe },
  { to: "/drawdown-shield", label: "Drawdown Shield", icon: Shield },
  { to: "/checklist", label: "Pre-Trade Checklist", icon: CheckSquare },
  { to: "/replay", label: "Scenario Tester", icon: Play },
  { to: "/walk-forward", label: "Walk-Forward", icon: Target },
  { to: "/music", label: "Music Studio", icon: Music },
] as const;

// Desktop grouped sections
const SECTIONS = [
  {
    title: "Trading Desk",
    icon: LayoutDashboard,
    items: [
      { to: "/", label: "Dashboard", icon: Gauge },
      { to: "/signals", label: "Signals", icon: Zap },
      { to: "/analysis", label: "Analysis", icon: Activity },
      { to: "/advanced-analysis", label: "Advanced Analysis", icon: Sparkles },
      { to: "/chart", label: "Live Chart", icon: LineChart },
      { to: "/heatmap", label: "Heatmap", icon: Flame },
      { to: "/technical-analysis", label: "Technical Analysis", icon: CandlestickChart },
    ],
  },
  {
    title: "AI & Scanners",
    icon: Cpu,
    items: [
      { to: "/chat", label: "AI Chat", icon: MessageSquare },
      { to: "/local-ai", label: "Local AI", icon: Brain },
      { to: "/neural", label: "Neural Net", icon: Brain },
      { to: "/ultra", label: "Ultra", icon: Sparkles },
      { to: "/smc", label: "SMC", icon: Layers },
      { to: "/scanner", label: "Scanner", icon: Radio },
      { to: "/persistence", label: "24/7 Scan", icon: InfinityIcon },
      { to: "/confluence", label: "Confluence", icon: Crosshair },
      { to: "/automation", label: "Automation", icon: Timer },
      { to: "/bot", label: "Auto-Bot", icon: Rocket },
    ],
  },
  {
    title: "Market Insights",
    icon: Globe,
    items: [
      { to: "/market-profile", label: "Market Profile", icon: BarChart3 },
      { to: "/dark-pool", label: "Dark Pool", icon: Eye },
      { to: "/options-flow", label: "Options", icon: DollarSign },
      { to: "/sentiment", label: "Sentiment", icon: Twitter },
      { to: "/sessions", label: "Sessions", icon: Globe },
      { to: "/currency-strength", label: "Strength", icon: Gauge },
      { to: "/calendar", label: "Calendar", icon: CalIcon },
    ],
  },
  {
    title: "Calculators",
    icon: Calculator,
    items: [
      { to: "/risk-calculator", label: "Risk Calc", icon: Calculator },
      { to: "/compound", label: "Growth Calc", icon: TrendingUp },
      { to: "/scaling", label: "Scale Out", icon: SplitSquareHorizontal },
      { to: "/margin", label: "Margin", icon: Landmark },
      { to: "/pip-value", label: "Pip Value", icon: Coins },
      { to: "/options-calc", label: "Black-Scholes", icon: Percent },
      { to: "/pivot", label: "Pivots", icon: ArrowUpFromLine },
      { to: "/fibonacci", label: "Fibonacci", icon: AlignJustify },
      { to: "/recovery", label: "Recovery", icon: LifeBuoy },
    ],
  },
  {
    title: "Strategy & Journal",
    icon: BookOpen,
    items: [
      { to: "/plan", label: "Trading Plan", icon: ListChecks },
      { to: "/journal", label: "Journal", icon: BookOpen },
      { to: "/pnl", label: "PnL Tracker", icon: TrendingUp },
      { to: "/backtest", label: "Backtester", icon: History },
      { to: "/optimizer", label: "Optimizer", icon: Wrench },
      { to: "/confluence", label: "Confluence", icon: Crosshair },
      { to: "/automation", label: "Automation", icon: Timer },
      { to: "/simulator", label: "Simulator", icon: Dices },
      { to: "/monte-carlo", label: "Monte Carlo", icon: Dices },
      { to: "/correlation", label: "Correlation", icon: Activity },
      { to: "/volatility", label: "Vol Regime", icon: Flame },
      { to: "/walk-forward", label: "Walk-Forward", icon: Target },
    ],
  },
  {
    title: "Risk & Psychology",
    icon: Shield,
    items: [
      { to: "/drawdown-shield", label: "Drawdown Shield", icon: Shield },
      { to: "/streak", label: "Streak Tracker", icon: Flame },
      { to: "/checklist", label: "Pre-Trade Checklist", icon: CheckSquare },
      { to: "/session-overlap", label: "Session Overlap", icon: Globe },
      { to: "/replay", label: "Scenario Tester", icon: Play },
    ],
  },
  {
    title: "Music & Audio",
    icon: Music,
    items: [
      { to: "/music", label: "Music Studio", icon: Music },
    ],
  },
  {
    title: "System Admin",
    icon: Settings,
    items: [
      { to: "/deriv", label: "Deriv API", icon: Wallet },
      { to: "/api-keys", label: "API Keys", icon: Key },
      { to: "/telegram", label: "Telegram", icon: Bot },
      { to: "/webhook-events", label: "Webhooks", icon: Shield },
      { to: "/docs", label: "API Docs", icon: BookOpen },
      { to: "/zo", label: "Zo Cloud", icon: Cpu },
      { to: "/system", label: "System Status", icon: Cpu },
      { to: "/dlq", label: "DLQ Admin", icon: Inbox },
      { to: "/alerts", label: "Alerts", icon: Bell },
      { to: "/mcp-servers", label: "MCP Servers", icon: Server },
    ],
  },
];

// Mobile bottom-tab layout: 4 primary + "More" sheet
const MOBILE_PRIMARY = [
  { to: "/", label: "Dash", icon: Gauge },
  { to: "/signals", label: "Signals", icon: Zap },
  { to: "/chat", label: "AI Chat", icon: MessageSquare },
