/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ZoRouteImport } from './routes/zo'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as WebhooksRouteImport } from './routes/webhooks'
import { Route as WebhookEventsRouteImport } from './routes/webhook-events'
import { Route as VolatilityRouteImport } from './routes/volatility'
import { Route as UptimeRouteImport } from './routes/uptime'
import { Route as UltraRouteImport } from './routes/ultra'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as TelegramRouteImport } from './routes/telegram'
import { Route as TechnicalAnalysisRouteImport } from './routes/technical-analysis'
import { Route as SystemRouteImport } from './routes/system'
import { Route as StreakRouteImport } from './routes/streak'
import { Route as StrategiesRouteImport } from './routes/strategies'
import { Route as SimulatorRouteImport } from './routes/simulator'
import { Route as SignalsRouteImport } from './routes/signals'
import { Route as SignalStatsRouteImport } from './routes/signal-stats'
import { Route as SessionsRouteImport } from './routes/sessions'
import { Route as SessionOverlapRouteImport } from './routes/session-overlap'
import { Route as SentimentRouteImport } from './routes/sentiment'
import { Route as ScreenerRouteImport } from './routes/screener'
import { Route as ScannerRouteImport } from './routes/scanner'
import { Route as ScalingRouteImport } from './routes/scaling'
import { Route as RiskCalculatorRouteImport } from './routes/risk-calculator'
import { Route as ReplayRouteImport } from './routes/replay'
import { Route as RecoveryRouteImport } from './routes/recovery'
import { Route as PnlRouteImport } from './routes/pnl'
import { Route as PlanRouteImport } from './routes/plan'
import { Route as PivotRouteImport } from './routes/pivot'
import { Route as PipValueRouteImport } from './routes/pip-value'
import { Route as PersistenceRouteImport } from './routes/persistence'
import { Route as PerformanceRouteImport } from './routes/performance'
import { Route as OptionsFlowRouteImport } from './routes/options-flow'
import { Route as OptionsCalcRouteImport } from './routes/options-calc'
import { Route as OptimizerRouteImport } from './routes/optimizer'
import { Route as OptimizationRouteImport } from './routes/optimization'
import { Route as NeuralRouteImport } from './routes/neural'
import { Route as MtfRouteImport } from './routes/mtf'
import { Route as MonteCarloRouteImport } from './routes/monte-carlo'
import { Route as McpServersRouteImport } from './routes/mcp-servers'
import { Route as MarketProfileRouteImport } from './routes/market-profile'
import { Route as MarginRouteImport } from './routes/margin'
import { Route as LocalAiRouteImport } from './routes/local-ai'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as HeatmapRouteImport } from './routes/heatmap'
import { Route as FibonacciRouteImport } from './routes/fibonacci'
import { Route as DrawdownShieldRouteImport } from './routes/drawdown-shield'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as DlqRouteImport } from './routes/dlq'
import { Route as DetectorsRouteImport } from './routes/detectors'
import { Route as DerivRouteImport } from './routes/deriv'
import { Route as DarkPoolRouteImport } from './routes/dark-pool'
import { Route as CurrencyStrengthRouteImport } from './routes/currency-strength'
import { Route as CorrelationRouteImport } from './routes/correlation'
import { Route as ConfluenceRouteImport } from './routes/confluence'
import { Route as CompoundRouteImport } from './routes/compound'
import { Route as ChecklistRouteImport } from './routes/checklist'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as ChartRouteImport } from './routes/chart'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as BotRouteImport } from './routes/bot'
import { Route as BoomCrashRouteImport } from './routes/boom-crash'
import { Route as BacktestRouteImport } from './routes/backtest'
import { Route as AutomationRouteImport } from './routes/automation'
import { Route as ApiKeysRouteImport } from './routes/api-keys'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AnalysisRouteImport } from './routes/analysis'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as AlertBuilderRouteImport } from './routes/alert-builder'
import { Route as AiAgentsRouteImport } from './routes/ai-agents'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicHealthRouteImport } from './routes/api/public/health'
import { Route as ApiKeepaliveZoRouteImport } from './routes/api/keepalive/zo'
import { Route as ApiPublicV1SignalsRouteImport } from './routes/api/public/v1/signals'
import { Route as ApiPublicV1AnalysisRouteImport } from './routes/api/public/v1/analysis'
import { Route as ApiPublicTelegramWebhookRouteImport } from './routes/api/public/telegram/webhook'
import { Route as ApiPublicHooksScanRouteImport } from './routes/api/public/hooks/scan'
import { Route as ApiPublicHooksReplayStatusRouteImport } from './routes/api/public/hooks/replay-status'
import { Route as ApiPublicHooksReplayDlqRouteImport } from './routes/api/public/hooks/replay-dlq'
import { Route as ApiPublicHooksReconcileTradesRouteImport } from './routes/api/public/hooks/reconcile-trades'
import { Route as ApiPublicHooksKeepaliveRouteImport } from './routes/api/public/hooks/keepalive'
import { Route as ApiPublicHooksExpireSignalsRouteImport } from './routes/api/public/hooks/expire-signals'
import { Route as ApiPublicV1WebhooksSubscribeRouteImport } from './routes/api/public/v1/webhooks/subscribe'
import { Route as ApiPublicV1SignalsIncomingRouteImport } from './routes/api/public/v1/signals/incoming'

const ZoRoute = ZoRouteImport.update({
  id: '/zo',
  path: '/zo',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const WebhooksRoute = WebhooksRouteImport.update({
  id: '/webhooks',
  path: '/webhooks',
  getParentRoute: () => rootRouteImport,
} as any)
const WebhookEventsRoute = WebhookEventsRouteImport.update({
  id: '/webhook-events',
  path: '/webhook-events',
  getParentRoute: () => rootRouteImport,
} as any)
const VolatilityRoute = VolatilityRouteImport.update({
  id: '/volatility',
  path: '/volatility',
  getParentRoute: () => rootRouteImport,
} as any)
const UptimeRoute = UptimeRouteImport.update({
  id: '/uptime',
  path: '/uptime',
  getParentRoute: () => rootRouteImport,
} as any)
const UltraRoute = UltraRouteImport.update({
  id: '/ultra',
  path: '/ultra',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const TelegramRoute = TelegramRouteImport.update({
  id: '/telegram',
  path: '/telegram',
  getParentRoute: () => rootRouteImport,
} as any)
const TechnicalAnalysisRoute = TechnicalAnalysisRouteImport.update({
  id: '/technical-analysis',
  path: '/technical-analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemRoute = SystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => rootRouteImport,
} as any)
const StreakRoute = StreakRouteImport.update({
  id: '/streak',
  path: '/streak',
  getParentRoute: () => rootRouteImport,
} as any)
const StrategiesRoute = StrategiesRouteImport.update({
  id: '/strategies',
  path: '/strategies',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulatorRoute = SimulatorRouteImport.update({
  id: '/simulator',
  path: '/simulator',
  getParentRoute: () => rootRouteImport,
} as any)
const SignalsRoute = SignalsRouteImport.update({
  id: '/signals',
  path: '/signals',
  getParentRoute: () => rootRouteImport,
} as any)
const SignalStatsRoute = SignalStatsRouteImport.update({
  id: '/signal-stats',
  path: '/signal-stats',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsRoute = SessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionOverlapRoute = SessionOverlapRouteImport.update({
  id: '/session-overlap',
  path: '/session-overlap',
  getParentRoute: () => rootRouteImport,
} as any)
const SentimentRoute = SentimentRouteImport.update({
  id: '/sentiment',
  path: '/sentiment',
  getParentRoute: () => rootRouteImport,
} as any)
const ScreenerRoute = ScreenerRouteImport.update({
  id: '/screener',
  path: '/screener',
  getParentRoute: () => rootRouteImport,
} as any)
const ScannerRoute = ScannerRouteImport.update({
  id: '/scanner',
  path: '/scanner',
  getParentRoute: () => rootRouteImport,
} as any)
const ScalingRoute = ScalingRouteImport.update({
  id: '/scaling',
  path: '/scaling',
  getParentRoute: () => rootRouteImport,
} as any)
const RiskCalculatorRoute = RiskCalculatorRouteImport.update({
  id: '/risk-calculator',
  path: '/risk-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const ReplayRoute = ReplayRouteImport.update({
  id: '/replay',
  path: '/replay',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoveryRoute = RecoveryRouteImport.update({
  id: '/recovery',
  path: '/recovery',
  getParentRoute: () => rootRouteImport,
} as any)
const PnlRoute = PnlRouteImport.update({
  id: '/pnl',
  path: '/pnl',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanRoute = PlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => rootRouteImport,
} as any)
const PivotRoute = PivotRouteImport.update({
  id: '/pivot',
  path: '/pivot',
  getParentRoute: () => rootRouteImport,
} as any)
const PipValueRoute = PipValueRouteImport.update({
  id: '/pip-value',
  path: '/pip-value',
  getParentRoute: () => rootRouteImport,
} as any)
const PersistenceRoute = PersistenceRouteImport.update({
  id: '/persistence',
  path: '/persistence',
  getParentRoute: () => rootRouteImport,
} as any)
const PerformanceRoute = PerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => rootRouteImport,
} as any)
const OptionsFlowRoute = OptionsFlowRouteImport.update({
  id: '/options-flow',
  path: '/options-flow',
  getParentRoute: () => rootRouteImport,
} as any)
const OptionsCalcRoute = OptionsCalcRouteImport.update({
  id: '/options-calc',
  path: '/options-calc',
  getParentRoute: () => rootRouteImport,
} as any)
const OptimizerRoute = OptimizerRouteImport.update({
  id: '/optimizer',
  path: '/optimizer',
  getParentRoute: () => rootRouteImport,
} as any)
const OptimizationRoute = OptimizationRouteImport.update({
  id: '/optimization',
  path: '/optimization',
  getParentRoute: () => rootRouteImport,
} as any)
const NeuralRoute = NeuralRouteImport.update({
  id: '/neural',
  path: '/neural',
  getParentRoute: () => rootRouteImport,
} as any)
const MtfRoute = MtfRouteImport.update({
  id: '/mtf',
  path: '/mtf',
  getParentRoute: () => rootRouteImport,
} as any)
const MonteCarloRoute = MonteCarloRouteImport.update({
  id: '/monte-carlo',
  path: '/monte-carlo',
  getParentRoute: () => rootRouteImport,
} as any)
const McpServersRoute = McpServersRouteImport.update({
  id: '/mcp-servers',
  path: '/mcp-servers',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketProfileRoute = MarketProfileRouteImport.update({
  id: '/market-profile',
  path: '/market-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MarginRoute = MarginRouteImport.update({
  id: '/margin',
  path: '/margin',
  getParentRoute: () => rootRouteImport,
} as any)
const LocalAiRoute = LocalAiRouteImport.update({
  id: '/local-ai',
  path: '/local-ai',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const HeatmapRoute = HeatmapRouteImport.update({
  id: '/heatmap',
  path: '/heatmap',
  getParentRoute: () => rootRouteImport,
} as any)
const FibonacciRoute = FibonacciRouteImport.update({
  id: '/fibonacci',
  path: '/fibonacci',
  getParentRoute: () => rootRouteImport,
} as any)
const DrawdownShieldRoute = DrawdownShieldRouteImport.update({
  id: '/drawdown-shield',
  path: '/drawdown-shield',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const DlqRoute = DlqRouteImport.update({
  id: '/dlq',
  path: '/dlq',
  getParentRoute: () => rootRouteImport,
} as any)
const DetectorsRoute = DetectorsRouteImport.update({
  id: '/detectors',
  path: '/detectors',
  getParentRoute: () => rootRouteImport,
} as any)
const DerivRoute = DerivRouteImport.update({
  id: '/deriv',
  path: '/deriv',
  getParentRoute: () => rootRouteImport,
} as any)
const DarkPoolRoute = DarkPoolRouteImport.update({
  id: '/dark-pool',
  path: '/dark-pool',
  getParentRoute: () => rootRouteImport,
} as any)
const CurrencyStrengthRoute = CurrencyStrengthRouteImport.update({
  id: '/currency-strength',
  path: '/currency-strength',
  getParentRoute: () => rootRouteImport,
} as any)
const CorrelationRoute = CorrelationRouteImport.update({
  id: '/correlation',
  path: '/correlation',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfluenceRoute = ConfluenceRouteImport.update({
  id: '/confluence',
  path: '/confluence',
  getParentRoute: () => rootRouteImport,
} as any)
const CompoundRoute = CompoundRouteImport.update({
  id: '/compound',
  path: '/compound',
  getParentRoute: () => rootRouteImport,
} as any)
const ChecklistRoute = ChecklistRouteImport.update({
  id: '/checklist',
  path: '/checklist',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ChartRoute = ChartRouteImport.update({
  id: '/chart',
  path: '/chart',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const BotRoute = BotRouteImport.update({
  id: '/bot',
  path: '/bot',
  getParentRoute: () => rootRouteImport,
} as any)
const BoomCrashRoute = BoomCrashRouteImport.update({
  id: '/boom-crash',
  path: '/boom-crash',
  getParentRoute: () => rootRouteImport,
} as any)
const BacktestRoute = BacktestRouteImport.update({
  id: '/backtest',
  path: '/backtest',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomationRoute = AutomationRouteImport.update({
  id: '/automation',
  path: '/automation',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKeysRoute = ApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysisRoute = AnalysisRouteImport.update({
  id: '/analysis',
  path: '/analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertBuilderRoute = AlertBuilderRouteImport.update({
  id: '/alert-builder',
  path: '/alert-builder',
  getParentRoute: () => rootRouteImport,
} as any)
const AiAgentsRoute = AiAgentsRouteImport.update({
  id: '/ai-agents',
  path: '/ai-agents',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHealthRoute = ApiPublicHealthRouteImport.update({
  id: '/api/public/health',
  path: '/api/public/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKeepaliveZoRoute = ApiKeepaliveZoRouteImport.update({
  id: '/api/keepalive/zo',
  path: '/api/keepalive/zo',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1SignalsRoute = ApiPublicV1SignalsRouteImport.update({
  id: '/api/public/v1/signals',
  path: '/api/public/v1/signals',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1AnalysisRoute = ApiPublicV1AnalysisRouteImport.update({
  id: '/api/public/v1/analysis',
  path: '/api/public/v1/analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTelegramWebhookRoute =
  ApiPublicTelegramWebhookRouteImport.update({
    id: '/api/public/telegram/webhook',
    path: '/api/public/telegram/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksScanRoute = ApiPublicHooksScanRouteImport.update({
  id: '/api/public/hooks/scan',
  path: '/api/public/hooks/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksReplayStatusRoute =
  ApiPublicHooksReplayStatusRouteImport.update({
    id: '/api/public/hooks/replay-status',
    path: '/api/public/hooks/replay-status',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksReplayDlqRoute = ApiPublicHooksReplayDlqRouteImport.update({
  id: '/api/public/hooks/replay-dlq',
  path: '/api/public/hooks/replay-dlq',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksReconcileTradesRoute =
  ApiPublicHooksReconcileTradesRouteImport.update({
    id: '/api/public/hooks/reconcile-trades',
    path: '/api/public/hooks/reconcile-trades',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksKeepaliveRoute = ApiPublicHooksKeepaliveRouteImport.update({
  id: '/api/public/hooks/keepalive',
  path: '/api/public/hooks/keepalive',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksExpireSignalsRoute =
  ApiPublicHooksExpireSignalsRouteImport.update({
    id: '/api/public/hooks/expire-signals',
    path: '/api/public/hooks/expire-signals',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicV1WebhooksSubscribeRoute =
  ApiPublicV1WebhooksSubscribeRouteImport.update({
    id: '/api/public/v1/webhooks/subscribe',
    path: '/api/public/v1/webhooks/subscribe',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicV1SignalsIncomingRoute =
  ApiPublicV1SignalsIncomingRouteImport.update({
    id: '/incoming',
    path: '/incoming',
    getParentRoute: () => ApiPublicV1SignalsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-agents': typeof AiAgentsRoute
  '/alert-builder': typeof AlertBuilderRoute
  '/alerts': typeof AlertsRoute
  '/analysis': typeof AnalysisRoute
  '/analytics': typeof AnalyticsRoute
  '/api-keys': typeof ApiKeysRoute
  '/automation': typeof AutomationRoute
  '/backtest': typeof BacktestRoute
  '/boom-crash': typeof BoomCrashRoute
  '/bot': typeof BotRoute
  '/calendar': typeof CalendarRoute
  '/chart': typeof ChartRoute
  '/chat': typeof ChatRoute
  '/checklist': typeof ChecklistRoute
  '/compound': typeof CompoundRoute
  '/confluence': typeof ConfluenceRoute
  '/correlation': typeof CorrelationRoute
  '/currency-strength': typeof CurrencyStrengthRoute
  '/dark-pool': typeof DarkPoolRoute
  '/deriv': typeof DerivRoute
  '/detectors': typeof DetectorsRoute
  '/dlq': typeof DlqRoute
  '/docs': typeof DocsRoute
  '/drawdown-shield': typeof DrawdownShieldRoute
  '/fibonacci': typeof FibonacciRoute
  '/heatmap': typeof HeatmapRoute
  '/journal': typeof JournalRoute
  '/local-ai': typeof LocalAiRoute
  '/margin': typeof MarginRoute
  '/market-profile': typeof MarketProfileRoute
  '/mcp-servers': typeof McpServersRoute
  '/monte-carlo': typeof MonteCarloRoute
  '/mtf': typeof MtfRoute
  '/neural': typeof NeuralRoute
  '/optimization': typeof OptimizationRoute
  '/optimizer': typeof OptimizerRoute
  '/options-calc': typeof OptionsCalcRoute
  '/options-flow': typeof OptionsFlowRoute
  '/performance': typeof PerformanceRoute
  '/persistence': typeof PersistenceRoute
  '/pip-value': typeof PipValueRoute
  '/pivot': typeof PivotRoute
  '/plan': typeof PlanRoute
  '/pnl': typeof PnlRoute
  '/recovery': typeof RecoveryRoute
  '/replay': typeof ReplayRoute
  '/risk-calculator': typeof RiskCalculatorRoute
  '/scaling': typeof ScalingRoute
  '/scanner': typeof ScannerRoute
  '/screener': typeof ScreenerRoute
  '/sentiment': typeof SentimentRoute
  '/session-overlap': typeof SessionOverlapRoute
  '/sessions': typeof SessionsRoute
  '/signal-stats': typeof SignalStatsRoute
  '/signals': typeof SignalsRoute
  '/simulator': typeof SimulatorRoute
  '/strategies': typeof StrategiesRoute
  '/streak': typeof StreakRoute
  '/system': typeof SystemRoute
  '/technical-analysis': typeof TechnicalAnalysisRoute
  '/telegram': typeof TelegramRoute
  '/tools': typeof ToolsRoute
  '/ultra': typeof UltraRoute
  '/uptime': typeof UptimeRoute
  '/volatility': typeof VolatilityRoute
  '/webhook-events': typeof WebhookEventsRoute
  '/webhooks': typeof WebhooksRoute
  '/welcome': typeof WelcomeRoute
  '/zo': typeof ZoRoute
  '/api/keepalive/zo': typeof ApiKeepaliveZoRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/hooks/expire-signals': typeof ApiPublicHooksExpireSignalsRoute
  '/api/public/hooks/keepalive': typeof ApiPublicHooksKeepaliveRoute
  '/api/public/hooks/reconcile-trades': typeof ApiPublicHooksReconcileTradesRoute
  '/api/public/hooks/replay-dlq': typeof ApiPublicHooksReplayDlqRoute
  '/api/public/hooks/replay-status': typeof ApiPublicHooksReplayStatusRoute
  '/api/public/hooks/scan': typeof ApiPublicHooksScanRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
  '/api/public/v1/analysis': typeof ApiPublicV1AnalysisRoute
  '/api/public/v1/signals': typeof ApiPublicV1SignalsRouteWithChildren
  '/api/public/v1/signals/incoming': typeof ApiPublicV1SignalsIncomingRoute
  '/api/public/v1/webhooks/subscribe': typeof ApiPublicV1WebhooksSubscribeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-agents': typeof AiAgentsRoute
  '/alert-builder': typeof AlertBuilderRoute
  '/alerts': typeof AlertsRoute
  '/analysis': typeof AnalysisRoute
  '/analytics': typeof AnalyticsRoute
  '/api-keys': typeof ApiKeysRoute
  '/automation': typeof AutomationRoute
  '/backtest': typeof BacktestRoute
  '/boom-crash': typeof BoomCrashRoute
  '/bot': typeof BotRoute
  '/calendar': typeof CalendarRoute
  '/chart': typeof ChartRoute
  '/chat': typeof ChatRoute
  '/checklist': typeof ChecklistRoute
  '/compound': typeof CompoundRoute
  '/confluence': typeof ConfluenceRoute
  '/correlation': typeof CorrelationRoute
  '/currency-strength': typeof CurrencyStrengthRoute
  '/dark-pool': typeof DarkPoolRoute
  '/deriv': typeof DerivRoute
  '/detectors': typeof DetectorsRoute
  '/dlq': typeof DlqRoute
  '/docs': typeof DocsRoute
  '/drawdown-shield': typeof DrawdownShieldRoute
  '/fibonacci': typeof FibonacciRoute
  '/heatmap': typeof HeatmapRoute
  '/journal': typeof JournalRoute
  '/local-ai': typeof LocalAiRoute
  '/margin': typeof MarginRoute
  '/market-profile': typeof MarketProfileRoute
  '/mcp-servers': typeof McpServersRoute
  '/monte-carlo': typeof MonteCarloRoute
  '/mtf': typeof MtfRoute
  '/neural': typeof NeuralRoute
  '/optimization': typeof OptimizationRoute
  '/optimizer': typeof OptimizerRoute
  '/options-calc': typeof OptionsCalcRoute
  '/options-flow': typeof OptionsFlowRoute
  '/performance': typeof PerformanceRoute
  '/persistence': typeof PersistenceRoute
  '/pip-value': typeof PipValueRoute
  '/pivot': typeof PivotRoute
  '/plan': typeof PlanRoute
  '/pnl': typeof PnlRoute
  '/recovery': typeof RecoveryRoute
  '/replay': typeof ReplayRoute
  '/risk-calculator': typeof RiskCalculatorRoute
  '/scaling': typeof ScalingRoute
  '/scanner': typeof ScannerRoute
  '/screener': typeof ScreenerRoute
  '/sentiment': typeof SentimentRoute
  '/session-overlap': typeof SessionOverlapRoute
  '/sessions': typeof SessionsRoute
  '/signal-stats': typeof SignalStatsRoute
  '/signals': typeof SignalsRoute
  '/simulator': typeof SimulatorRoute
  '/strategies': typeof StrategiesRoute
  '/streak': typeof StreakRoute
  '/system': typeof SystemRoute
  '/technical-analysis': typeof TechnicalAnalysisRoute
  '/telegram': typeof TelegramRoute
  '/tools': typeof ToolsRoute
  '/ultra': typeof UltraRoute
  '/uptime': typeof UptimeRoute
  '/volatility': typeof VolatilityRoute
  '/webhook-events': typeof WebhookEventsRoute
  '/webhooks': typeof WebhooksRoute
  '/welcome': typeof WelcomeRoute
  '/zo': typeof ZoRoute
  '/api/keepalive/zo': typeof ApiKeepaliveZoRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/hooks/expire-signals': typeof ApiPublicHooksExpireSignalsRoute
  '/api/public/hooks/keepalive': typeof ApiPublicHooksKeepaliveRoute
  '/api/public/hooks/reconcile-trades': typeof ApiPublicHooksReconcileTradesRoute
  '/api/public/hooks/replay-dlq': typeof ApiPublicHooksReplayDlqRoute
  '/api/public/hooks/replay-status': typeof ApiPublicHooksReplayStatusRoute
  '/api/public/hooks/scan': typeof ApiPublicHooksScanRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
  '/api/public/v1/analysis': typeof ApiPublicV1AnalysisRoute
  '/api/public/v1/signals': typeof ApiPublicV1SignalsRouteWithChildren
  '/api/public/v1/signals/incoming': typeof ApiPublicV1SignalsIncomingRoute
  '/api/public/v1/webhooks/subscribe': typeof ApiPublicV1WebhooksSubscribeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-agents': typeof AiAgentsRoute
  '/alert-builder': typeof AlertBuilderRoute
  '/alerts': typeof AlertsRoute
  '/analysis': typeof AnalysisRoute
  '/analytics': typeof AnalyticsRoute
  '/api-keys': typeof ApiKeysRoute
  '/automation': typeof AutomationRoute
  '/backtest': typeof BacktestRoute
  '/boom-crash': typeof BoomCrashRoute
  '/bot': typeof BotRoute
  '/calendar': typeof CalendarRoute
  '/chart': typeof ChartRoute
  '/chat': typeof ChatRoute
  '/checklist': typeof ChecklistRoute
  '/compound': typeof CompoundRoute
  '/confluence': typeof ConfluenceRoute
  '/correlation': typeof CorrelationRoute
  '/currency-strength': typeof CurrencyStrengthRoute
  '/dark-pool': typeof DarkPoolRoute
  '/deriv': typeof DerivRoute
  '/detectors': typeof DetectorsRoute
  '/dlq': typeof DlqRoute
  '/docs': typeof DocsRoute
  '/drawdown-shield': typeof DrawdownShieldRoute
  '/fibonacci': typeof FibonacciRoute
  '/heatmap': typeof HeatmapRoute
  '/journal': typeof JournalRoute
  '/local-ai': typeof LocalAiRoute
  '/margin': typeof MarginRoute
  '/market-profile': typeof MarketProfileRoute
  '/mcp-servers': typeof McpServersRoute
  '/monte-carlo': typeof MonteCarloRoute
  '/mtf': typeof MtfRoute
  '/neural': typeof NeuralRoute
  '/optimization': typeof OptimizationRoute
  '/optimizer': typeof OptimizerRoute
  '/options-calc': typeof OptionsCalcRoute
  '/options-flow': typeof OptionsFlowRoute
  '/performance': typeof PerformanceRoute
  '/persistence': typeof PersistenceRoute
  '/pip-value': typeof PipValueRoute
  '/pivot': typeof PivotRoute
  '/plan': typeof PlanRoute
  '/pnl': typeof PnlRoute
  '/recovery': typeof RecoveryRoute
  '/replay': typeof ReplayRoute
  '/risk-calculator': typeof RiskCalculatorRoute
  '/scaling': typeof ScalingRoute
  '/scanner': typeof ScannerRoute
  '/screener': typeof ScreenerRoute
  '/sentiment': typeof SentimentRoute
  '/session-overlap': typeof SessionOverlapRoute
  '/sessions': typeof SessionsRoute
  '/signal-stats': typeof SignalStatsRoute
  '/signals': typeof SignalsRoute
  '/simulator': typeof SimulatorRoute
  '/strategies': typeof StrategiesRoute
  '/streak': typeof StreakRoute
  '/system': typeof SystemRoute
  '/technical-analysis': typeof TechnicalAnalysisRoute
  '/telegram': typeof TelegramRoute
  '/tools': typeof ToolsRoute
  '/ultra': typeof UltraRoute
  '/uptime': typeof UptimeRoute
  '/volatility': typeof VolatilityRoute
  '/webhook-events': typeof WebhookEventsRoute
  '/webhooks': typeof WebhooksRoute
  '/welcome': typeof WelcomeRoute
  '/zo': typeof ZoRoute
  '/api/keepalive/zo': typeof ApiKeepaliveZoRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/hooks/expire-signals': typeof ApiPublicHooksExpireSignalsRoute
  '/api/public/hooks/keepalive': typeof ApiPublicHooksKeepaliveRoute
  '/api/public/hooks/reconcile-trades': typeof ApiPublicHooksReconcileTradesRoute
  '/api/public/hooks/replay-dlq': typeof ApiPublicHooksReplayDlqRoute
  '/api/public/hooks/replay-status': typeof ApiPublicHooksReplayStatusRoute
  '/api/public/hooks/scan': typeof ApiPublicHooksScanRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
  '/api/public/v1/analysis': typeof ApiPublicV1AnalysisRoute
  '/api/public/v1/signals': typeof ApiPublicV1SignalsRouteWithChildren
  '/api/public/v1/signals/incoming': typeof ApiPublicV1SignalsIncomingRoute
  '/api/public/v1/webhooks/subscribe': typeof ApiPublicV1WebhooksSubscribeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-agents'
    | '/alert-builder'
    | '/alerts'
    | '/analysis'
    | '/analytics'
    | '/api-keys'
    | '/automation'
    | '/backtest'
    | '/boom-crash'
    | '/bot'
    | '/calendar'
    | '/chart'
    | '/chat'
    | '/checklist'
    | '/compound'
    | '/confluence'
    | '/correlation'
    | '/currency-strength'
    | '/dark-pool'
    | '/deriv'
    | '/detectors'
    | '/dlq'
    | '/docs'
    | '/drawdown-shield'
    | '/fibonacci'
    | '/heatmap'
    | '/journal'
    | '/local-ai'
    | '/margin'
    | '/market-profile'
    | '/mcp-servers'
    | '/monte-carlo'
    | '/mtf'
    | '/neural'
    | '/optimization'
    | '/optimizer'
    | '/options-calc'
    | '/options-flow'
    | '/performance'
    | '/persistence'
    | '/pip-value'
    | '/pivot'
    | '/plan'
    | '/pnl'
    | '/recovery'
    | '/replay'
    | '/risk-calculator'
    | '/scaling'
    | '/scanner'
    | '/screener'
    | '/sentiment'
    | '/session-overlap'
    | '/sessions'
    | '/signal-stats'
    | '/signals'
    | '/simulator'
    | '/strategies'
    | '/streak'
    | '/system'
    | '/technical-analysis'
    | '/telegram'
    | '/tools'
    | '/ultra'
    | '/uptime'
    | '/volatility'
    | '/webhook-events'
    | '/webhooks'
    | '/welcome'
    | '/zo'
    | '/api/keepalive/zo'
    | '/api/public/health'
    | '/api/public/hooks/expire-signals'
    | '/api/public/hooks/keepalive'
    | '/api/public/hooks/reconcile-trades'
    | '/api/public/hooks/replay-dlq'
    | '/api/public/hooks/replay-status'
    | '/api/public/hooks/scan'
    | '/api/public/telegram/webhook'
    | '/api/public/v1/analysis'
    | '/api/public/v1/signals'
    | '/api/public/v1/signals/incoming'
    | '/api/public/v1/webhooks/subscribe'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-agents'
    | '/alert-builder'
    | '/alerts'
    | '/analysis'
    | '/analytics'
    | '/api-keys'
    | '/automation'
    | '/backtest'
    | '/boom-crash'
    | '/bot'
    | '/calendar'
    | '/chart'
    | '/chat'
    | '/checklist'
    | '/compound'
    | '/confluence'
    | '/correlation'
    | '/currency-strength'
    | '/dark-pool'
    | '/deriv'
    | '/detectors'
    | '/dlq'
    | '/docs'
    | '/drawdown-shield'
    | '/fibonacci'
    | '/heatmap'
    | '/journal'
    | '/local-ai'
    | '/margin'
    | '/market-profile'
    | '/mcp-servers'
    | '/monte-carlo'
    | '/mtf'
    | '/neural'
    | '/optimization'
    | '/optimizer'
    | '/options-calc'
    | '/options-flow'
    | '/performance'
    | '/persistence'
    | '/pip-value'
    | '/pivot'
    | '/plan'
    | '/pnl'
    | '/recovery'
    | '/replay'
    | '/risk-calculator'
    | '/scaling'
    | '/scanner'
    | '/screener'
    | '/sentiment'
    | '/session-overlap'
    | '/sessions'
    | '/signal-stats'
    | '/signals'
    | '/simulator'
    | '/strategies'
    | '/streak'
    | '/system'
    | '/technical-analysis'
    | '/telegram'
    | '/tools'
    | '/ultra'
    | '/uptime'
    | '/volatility'
    | '/webhook-events'
    | '/webhooks'
    | '/welcome'
    | '/zo'
    | '/api/keepalive/zo'
    | '/api/public/health'
    | '/api/public/hooks/expire-signals'
    | '/api/public/hooks/keepalive'
    | '/api/public/hooks/reconcile-trades'
    | '/api/public/hooks/replay-dlq'
    | '/api/public/hooks/replay-status'
    | '/api/public/hooks/scan'
    | '/api/public/telegram/webhook'
    | '/api/public/v1/analysis'
    | '/api/public/v1/signals'
    | '/api/public/v1/signals/incoming'
    | '/api/public/v1/webhooks/subscribe'
  id:
    | '__root__'
    | '/'
    | '/ai-agents'
    | '/alert-builder'
    | '/alerts'
    | '/analysis'
    | '/analytics'
    | '/api-keys'
    | '/automation'
    | '/backtest'
    | '/boom-crash'
    | '/bot'
    | '/calendar'
    | '/chart'
    | '/chat'
    | '/checklist'
    | '/compound'
    | '/confluence'
    | '/correlation'
    | '/currency-strength'
    | '/dark-pool'
    | '/deriv'
    | '/detectors'
    | '/dlq'
    | '/docs'
    | '/drawdown-shield'
    | '/fibonacci'
    | '/heatmap'
    | '/journal'
    | '/local-ai'
    | '/margin'
    | '/market-profile'
    | '/mcp-servers'
    | '/monte-carlo'
    | '/mtf'
    | '/neural'
    | '/optimization'
    | '/optimizer'
    | '/options-calc'
    | '/options-flow'
    | '/performance'
    | '/persistence'
    | '/pip-value'
    | '/pivot'
    | '/plan'
    | '/pnl'
    | '/recovery'
    | '/replay'
    | '/risk-calculator'
    | '/scaling'
    | '/scanner'
    | '/screener'
    | '/sentiment'
    | '/session-overlap'
    | '/sessions'
    | '/signal-stats'
    | '/signals'
    | '/simulator'
    | '/strategies'
    | '/streak'
    | '/system'
    | '/technical-analysis'
    | '/telegram'
    | '/tools'
    | '/ultra'
    | '/uptime'
    | '/volatility'
    | '/webhook-events'
    | '/webhooks'
    | '/welcome'
    | '/zo'
    | '/api/keepalive/zo'
    | '/api/public/health'
    | '/api/public/hooks/expire-signals'
    | '/api/public/hooks/keepalive'
    | '/api/public/hooks/reconcile-trades'
    | '/api/public/hooks/replay-dlq'
    | '/api/public/hooks/replay-status'
    | '/api/public/hooks/scan'
    | '/api/public/telegram/webhook'
    | '/api/public/v1/analysis'
    | '/api/public/v1/signals'
    | '/api/public/v1/signals/incoming'
    | '/api/public/v1/webhooks/subscribe'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiAgentsRoute: typeof AiAgentsRoute
  AlertBuilderRoute: typeof AlertBuilderRoute
  AlertsRoute: typeof AlertsRoute
  AnalysisRoute: typeof AnalysisRoute
  AnalyticsRoute: typeof AnalyticsRoute
  ApiKeysRoute: typeof ApiKeysRoute
  AutomationRoute: typeof AutomationRoute
  BacktestRoute: typeof BacktestRoute
  BoomCrashRoute: typeof BoomCrashRoute
  BotRoute: typeof BotRoute
  CalendarRoute: typeof CalendarRoute
  ChartRoute: typeof ChartRoute
  ChatRoute: typeof ChatRoute
  ChecklistRoute: typeof ChecklistRoute
  CompoundRoute: typeof CompoundRoute
  ConfluenceRoute: typeof ConfluenceRoute
  CorrelationRoute: typeof CorrelationRoute
  CurrencyStrengthRoute: typeof CurrencyStrengthRoute
  DarkPoolRoute: typeof DarkPoolRoute
  DerivRoute: typeof DerivRoute
  DetectorsRoute: typeof DetectorsRoute
  DlqRoute: typeof DlqRoute
  DocsRoute: typeof DocsRoute
  DrawdownShieldRoute: typeof DrawdownShieldRoute
  FibonacciRoute: typeof FibonacciRoute
  HeatmapRoute: typeof HeatmapRoute
  JournalRoute: typeof JournalRoute
  LocalAiRoute: typeof LocalAiRoute
  MarginRoute: typeof MarginRoute
  MarketProfileRoute: typeof MarketProfileRoute
  McpServersRoute: typeof McpServersRoute
  MonteCarloRoute: typeof MonteCarloRoute
  MtfRoute: typeof MtfRoute
  NeuralRoute: typeof NeuralRoute
  OptimizationRoute: typeof OptimizationRoute
  OptimizerRoute: typeof OptimizerRoute
  OptionsCalcRoute: typeof OptionsCalcRoute
  OptionsFlowRoute: typeof OptionsFlowRoute
  PerformanceRoute: typeof PerformanceRoute
  PersistenceRoute: typeof PersistenceRoute
  PipValueRoute: typeof PipValueRoute
  PivotRoute: typeof PivotRoute
  PlanRoute: typeof PlanRoute
  PnlRoute: typeof PnlRoute
  RecoveryRoute: typeof RecoveryRoute
  ReplayRoute: typeof ReplayRoute
  RiskCalculatorRoute: typeof RiskCalculatorRoute
  ScalingRoute: typeof ScalingRoute
  ScannerRoute: typeof ScannerRoute
  ScreenerRoute: typeof ScreenerRoute
  SentimentRoute: typeof SentimentRoute
  SessionOverlapRoute: typeof SessionOverlapRoute
  SessionsRoute: typeof SessionsRoute
  SignalStatsRoute: typeof SignalStatsRoute
  SignalsRoute: typeof SignalsRoute
  SimulatorRoute: typeof SimulatorRoute
  StrategiesRoute: typeof StrategiesRoute
  StreakRoute: typeof StreakRoute
  SystemRoute: typeof SystemRoute
  TechnicalAnalysisRoute: typeof TechnicalAnalysisRoute
  TelegramRoute: typeof TelegramRoute
  ToolsRoute: typeof ToolsRoute
  UltraRoute: typeof UltraRoute
  UptimeRoute: typeof UptimeRoute
  VolatilityRoute: typeof VolatilityRoute
  WebhookEventsRoute: typeof WebhookEventsRoute
  WebhooksRoute: typeof WebhooksRoute
  WelcomeRoute: typeof WelcomeRoute
  ZoRoute: typeof ZoRoute
  ApiKeepaliveZoRoute: typeof ApiKeepaliveZoRoute
  ApiPublicHealthRoute: typeof ApiPublicHealthRoute
  ApiPublicHooksExpireSignalsRoute: typeof ApiPublicHooksExpireSignalsRoute
  ApiPublicHooksKeepaliveRoute: typeof ApiPublicHooksKeepaliveRoute
  ApiPublicHooksReconcileTradesRoute: typeof ApiPublicHooksReconcileTradesRoute
  ApiPublicHooksReplayDlqRoute: typeof ApiPublicHooksReplayDlqRoute
  ApiPublicHooksReplayStatusRoute: typeof ApiPublicHooksReplayStatusRoute
  ApiPublicHooksScanRoute: typeof ApiPublicHooksScanRoute
  ApiPublicTelegramWebhookRoute: typeof ApiPublicTelegramWebhookRoute
  ApiPublicV1AnalysisRoute: typeof ApiPublicV1AnalysisRoute
  ApiPublicV1SignalsRoute: typeof ApiPublicV1SignalsRouteWithChildren
  ApiPublicV1WebhooksSubscribeRoute: typeof ApiPublicV1WebhooksSubscribeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/zo': {
      id: '/zo'
      path: '/zo'
      fullPath: '/zo'
      preLoaderRoute: typeof ZoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/webhooks': {
      id: '/webhooks'
      path: '/webhooks'
      fullPath: '/webhooks'
      preLoaderRoute: typeof WebhooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/webhook-events': {
      id: '/webhook-events'
      path: '/webhook-events'
      fullPath: '/webhook-events'
      preLoaderRoute: typeof WebhookEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/volatility': {
      id: '/volatility'
      path: '/volatility'
      fullPath: '/volatility'
      preLoaderRoute: typeof VolatilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uptime': {
      id: '/uptime'
      path: '/uptime'
      fullPath: '/uptime'
      preLoaderRoute: typeof UptimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ultra': {
      id: '/ultra'
      path: '/ultra'
      fullPath: '/ultra'
      preLoaderRoute: typeof UltraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/telegram': {
      id: '/telegram'
      path: '/telegram'
      fullPath: '/telegram'
      preLoaderRoute: typeof TelegramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/technical-analysis': {
      id: '/technical-analysis'
      path: '/technical-analysis'
      fullPath: '/technical-analysis'
      preLoaderRoute: typeof TechnicalAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system': {
      id: '/system'
      path: '/system'
      fullPath: '/system'
      preLoaderRoute: typeof SystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/streak': {
      id: '/streak'
      path: '/streak'
      fullPath: '/streak'
      preLoaderRoute: typeof StreakRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/strategies': {
      id: '/strategies'
      path: '/strategies'
      fullPath: '/strategies'
      preLoaderRoute: typeof StrategiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulator': {
      id: '/simulator'
      path: '/simulator'
      fullPath: '/simulator'
      preLoaderRoute: typeof SimulatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signals': {
      id: '/signals'
      path: '/signals'
      fullPath: '/signals'
      preLoaderRoute: typeof SignalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signal-stats': {
      id: '/signal-stats'
      path: '/signal-stats'
      fullPath: '/signal-stats'
      preLoaderRoute: typeof SignalStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions': {
      id: '/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof SessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session-overlap': {
      id: '/session-overlap'
      path: '/session-overlap'
      fullPath: '/session-overlap'
      preLoaderRoute: typeof SessionOverlapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sentiment': {
      id: '/sentiment'
      path: '/sentiment'
      fullPath: '/sentiment'
      preLoaderRoute: typeof SentimentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/screener': {
      id: '/screener'
      path: '/screener'
      fullPath: '/screener'
      preLoaderRoute: typeof ScreenerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scanner': {
      id: '/scanner'
      path: '/scanner'
      fullPath: '/scanner'
      preLoaderRoute: typeof ScannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scaling': {
      id: '/scaling'
      path: '/scaling'
      fullPath: '/scaling'
      preLoaderRoute: typeof ScalingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/risk-calculator': {
      id: '/risk-calculator'
      path: '/risk-calculator'
      fullPath: '/risk-calculator'
      preLoaderRoute: typeof RiskCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/replay': {
      id: '/replay'
      path: '/replay'
      fullPath: '/replay'
      preLoaderRoute: typeof ReplayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recovery': {
      id: '/recovery'
      path: '/recovery'
      fullPath: '/recovery'
      preLoaderRoute: typeof RecoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pnl': {
      id: '/pnl'
      path: '/pnl'
      fullPath: '/pnl'
      preLoaderRoute: typeof PnlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan': {
      id: '/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof PlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pivot': {
      id: '/pivot'
      path: '/pivot'
      fullPath: '/pivot'
      preLoaderRoute: typeof PivotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pip-value': {
      id: '/pip-value'
      path: '/pip-value'
      fullPath: '/pip-value'
      preLoaderRoute: typeof PipValueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/persistence': {
      id: '/persistence'
      path: '/persistence'
      fullPath: '/persistence'
      preLoaderRoute: typeof PersistenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/performance': {
      id: '/performance'
      path: '/performance'
      fullPath: '/performance'
      preLoaderRoute: typeof PerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/options-flow': {
      id: '/options-flow'
      path: '/options-flow'
      fullPath: '/options-flow'
      preLoaderRoute: typeof OptionsFlowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/options-calc': {
      id: '/options-calc'
      path: '/options-calc'
      fullPath: '/options-calc'
      preLoaderRoute: typeof OptionsCalcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/optimizer': {
      id: '/optimizer'
      path: '/optimizer'
      fullPath: '/optimizer'
      preLoaderRoute: typeof OptimizerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/optimization': {
      id: '/optimization'
      path: '/optimization'
      fullPath: '/optimization'
      preLoaderRoute: typeof OptimizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/neural': {
      id: '/neural'
      path: '/neural'
      fullPath: '/neural'
      preLoaderRoute: typeof NeuralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mtf': {
      id: '/mtf'
      path: '/mtf'
      fullPath: '/mtf'
      preLoaderRoute: typeof MtfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monte-carlo': {
      id: '/monte-carlo'
      path: '/monte-carlo'
      fullPath: '/monte-carlo'
      preLoaderRoute: typeof MonteCarloRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp-servers': {
      id: '/mcp-servers'
      path: '/mcp-servers'
      fullPath: '/mcp-servers'
      preLoaderRoute: typeof McpServersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market-profile': {
      id: '/market-profile'
      path: '/market-profile'
      fullPath: '/market-profile'
      preLoaderRoute: typeof MarketProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/margin': {
      id: '/margin'
      path: '/margin'
      fullPath: '/margin'
      preLoaderRoute: typeof MarginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/local-ai': {
      id: '/local-ai'
      path: '/local-ai'
      fullPath: '/local-ai'
      preLoaderRoute: typeof LocalAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/heatmap': {
      id: '/heatmap'
      path: '/heatmap'
      fullPath: '/heatmap'
      preLoaderRoute: typeof HeatmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fibonacci': {
      id: '/fibonacci'
      path: '/fibonacci'
      fullPath: '/fibonacci'
      preLoaderRoute: typeof FibonacciRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drawdown-shield': {
      id: '/drawdown-shield'
      path: '/drawdown-shield'
      fullPath: '/drawdown-shield'
      preLoaderRoute: typeof DrawdownShieldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dlq': {
      id: '/dlq'
      path: '/dlq'
      fullPath: '/dlq'
      preLoaderRoute: typeof DlqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/detectors': {
      id: '/detectors'
      path: '/detectors'
      fullPath: '/detectors'
      preLoaderRoute: typeof DetectorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deriv': {
      id: '/deriv'
      path: '/deriv'
      fullPath: '/deriv'
      preLoaderRoute: typeof DerivRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dark-pool': {
      id: '/dark-pool'
      path: '/dark-pool'
      fullPath: '/dark-pool'
      preLoaderRoute: typeof DarkPoolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/currency-strength': {
      id: '/currency-strength'
      path: '/currency-strength'
      fullPath: '/currency-strength'
      preLoaderRoute: typeof CurrencyStrengthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/correlation': {
      id: '/correlation'
      path: '/correlation'
      fullPath: '/correlation'
      preLoaderRoute: typeof CorrelationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confluence': {
      id: '/confluence'
      path: '/confluence'
      fullPath: '/confluence'
      preLoaderRoute: typeof ConfluenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compound': {
      id: '/compound'
      path: '/compound'
      fullPath: '/compound'
      preLoaderRoute: typeof CompoundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checklist': {
      id: '/checklist'
      path: '/checklist'
      fullPath: '/checklist'
      preLoaderRoute: typeof ChecklistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chart': {
      id: '/chart'
      path: '/chart'
      fullPath: '/chart'
      preLoaderRoute: typeof ChartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bot': {
      id: '/bot'
      path: '/bot'
      fullPath: '/bot'
      preLoaderRoute: typeof BotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boom-crash': {
      id: '/boom-crash'
      path: '/boom-crash'
      fullPath: '/boom-crash'
      preLoaderRoute: typeof BoomCrashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backtest': {
      id: '/backtest'
      path: '/backtest'
      fullPath: '/backtest'
      preLoaderRoute: typeof BacktestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automation': {
      id: '/automation'
      path: '/automation'
      fullPath: '/automation'
      preLoaderRoute: typeof AutomationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-keys': {
      id: '/api-keys'
      path: '/api-keys'
      fullPath: '/api-keys'
      preLoaderRoute: typeof ApiKeysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analysis': {
      id: '/analysis'
      path: '/analysis'
      fullPath: '/analysis'
      preLoaderRoute: typeof AnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alert-builder': {
      id: '/alert-builder'
      path: '/alert-builder'
      fullPath: '/alert-builder'
      preLoaderRoute: typeof AlertBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-agents': {
      id: '/ai-agents'
      path: '/ai-agents'
      fullPath: '/ai-agents'
      preLoaderRoute: typeof AiAgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/health': {
      id: '/api/public/health'
      path: '/api/public/health'
      fullPath: '/api/public/health'
      preLoaderRoute: typeof ApiPublicHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/keepalive/zo': {
      id: '/api/keepalive/zo'
      path: '/api/keepalive/zo'
      fullPath: '/api/keepalive/zo'
      preLoaderRoute: typeof ApiKeepaliveZoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/signals': {
      id: '/api/public/v1/signals'
      path: '/api/public/v1/signals'
      fullPath: '/api/public/v1/signals'
      preLoaderRoute: typeof ApiPublicV1SignalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/analysis': {
      id: '/api/public/v1/analysis'
      path: '/api/public/v1/analysis'
      fullPath: '/api/public/v1/analysis'
      preLoaderRoute: typeof ApiPublicV1AnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/telegram/webhook': {
      id: '/api/public/telegram/webhook'
      path: '/api/public/telegram/webhook'
      fullPath: '/api/public/telegram/webhook'
      preLoaderRoute: typeof ApiPublicTelegramWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/scan': {
      id: '/api/public/hooks/scan'
      path: '/api/public/hooks/scan'
      fullPath: '/api/public/hooks/scan'
      preLoaderRoute: typeof ApiPublicHooksScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/replay-status': {
      id: '/api/public/hooks/replay-status'
      path: '/api/public/hooks/replay-status'
      fullPath: '/api/public/hooks/replay-status'
      preLoaderRoute: typeof ApiPublicHooksReplayStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/replay-dlq': {
      id: '/api/public/hooks/replay-dlq'
      path: '/api/public/hooks/replay-dlq'
      fullPath: '/api/public/hooks/replay-dlq'
      preLoaderRoute: typeof ApiPublicHooksReplayDlqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/reconcile-trades': {
      id: '/api/public/hooks/reconcile-trades'
      path: '/api/public/hooks/reconcile-trades'
      fullPath: '/api/public/hooks/reconcile-trades'
      preLoaderRoute: typeof ApiPublicHooksReconcileTradesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/keepalive': {
      id: '/api/public/hooks/keepalive'
      path: '/api/public/hooks/keepalive'
      fullPath: '/api/public/hooks/keepalive'
      preLoaderRoute: typeof ApiPublicHooksKeepaliveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/expire-signals': {
      id: '/api/public/hooks/expire-signals'
      path: '/api/public/hooks/expire-signals'
      fullPath: '/api/public/hooks/expire-signals'
      preLoaderRoute: typeof ApiPublicHooksExpireSignalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/webhooks/subscribe': {
      id: '/api/public/v1/webhooks/subscribe'
      path: '/api/public/v1/webhooks/subscribe'
      fullPath: '/api/public/v1/webhooks/subscribe'
      preLoaderRoute: typeof ApiPublicV1WebhooksSubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/signals/incoming': {
      id: '/api/public/v1/signals/incoming'
      path: '/incoming'
      fullPath: '/api/public/v1/signals/incoming'
      preLoaderRoute: typeof ApiPublicV1SignalsIncomingRouteImport
      parentRoute: typeof ApiPublicV1SignalsRoute
    }
  }
}

interface ApiPublicV1SignalsRouteChildren {
  ApiPublicV1SignalsIncomingRoute: typeof ApiPublicV1SignalsIncomingRoute
}

const ApiPublicV1SignalsRouteChildren: ApiPublicV1SignalsRouteChildren = {
  ApiPublicV1SignalsIncomingRoute: ApiPublicV1SignalsIncomingRoute,
}

const ApiPublicV1SignalsRouteWithChildren =
  ApiPublicV1SignalsRoute._addFileChildren(ApiPublicV1SignalsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiAgentsRoute: AiAgentsRoute,
  AlertBuilderRoute: AlertBuilderRoute,
  AlertsRoute: AlertsRoute,
  AnalysisRoute: AnalysisRoute,
  AnalyticsRoute: AnalyticsRoute,
  ApiKeysRoute: ApiKeysRoute,
  AutomationRoute: AutomationRoute,
  BacktestRoute: BacktestRoute,
  BoomCrashRoute: BoomCrashRoute,
  BotRoute: BotRoute,
  CalendarRoute: CalendarRoute,
  ChartRoute: ChartRoute,
  ChatRoute: ChatRoute,
  ChecklistRoute: ChecklistRoute,
  CompoundRoute: CompoundRoute,
  ConfluenceRoute: ConfluenceRoute,
  CorrelationRoute: CorrelationRoute,
  CurrencyStrengthRoute: CurrencyStrengthRoute,
  DarkPoolRoute: DarkPoolRoute,
  DerivRoute: DerivRoute,
  DetectorsRoute: DetectorsRoute,
  DlqRoute: DlqRoute,
  DocsRoute: DocsRoute,
  DrawdownShieldRoute: DrawdownShieldRoute,
  FibonacciRoute: FibonacciRoute,
  HeatmapRoute: HeatmapRoute,
  JournalRoute: JournalRoute,
  LocalAiRoute: LocalAiRoute,
  MarginRoute: MarginRoute,
  MarketProfileRoute: MarketProfileRoute,
  McpServersRoute: McpServersRoute,
  MonteCarloRoute: MonteCarloRoute,
  MtfRoute: MtfRoute,
  NeuralRoute: NeuralRoute,
  OptimizationRoute: OptimizationRoute,
  OptimizerRoute: OptimizerRoute,
  OptionsCalcRoute: OptionsCalcRoute,
  OptionsFlowRoute: OptionsFlowRoute,
  PerformanceRoute: PerformanceRoute,
  PersistenceRoute: PersistenceRoute,
  PipValueRoute: PipValueRoute,
  PivotRoute: PivotRoute,
  PlanRoute: PlanRoute,
  PnlRoute: PnlRoute,
  RecoveryRoute: RecoveryRoute,
  ReplayRoute: ReplayRoute,
  RiskCalculatorRoute: RiskCalculatorRoute,
  ScalingRoute: ScalingRoute,
  ScannerRoute: ScannerRoute,
  ScreenerRoute: ScreenerRoute,
  SentimentRoute: SentimentRoute,
  SessionOverlapRoute: SessionOverlapRoute,
  SessionsRoute: SessionsRoute,
  SignalStatsRoute: SignalStatsRoute,
  SignalsRoute: SignalsRoute,
  SimulatorRoute: SimulatorRoute,
  StrategiesRoute: StrategiesRoute,
  StreakRoute: StreakRoute,
  SystemRoute: SystemRoute,
  TechnicalAnalysisRoute: TechnicalAnalysisRoute,
  TelegramRoute: TelegramRoute,
  ToolsRoute: ToolsRoute,
  UltraRoute: UltraRoute,
  UptimeRoute: UptimeRoute,
  VolatilityRoute: VolatilityRoute,
  WebhookEventsRoute: WebhookEventsRoute,
  WebhooksRoute: WebhooksRoute,
  WelcomeRoute: WelcomeRoute,
  ZoRoute: ZoRoute,
  ApiKeepaliveZoRoute: ApiKeepaliveZoRoute,
  ApiPublicHealthRoute: ApiPublicHealthRoute,
  ApiPublicHooksExpireSignalsRoute: ApiPublicHooksExpireSignalsRoute,
  ApiPublicHooksKeepaliveRoute: ApiPublicHooksKeepaliveRoute,
  ApiPublicHooksReconcileTradesRoute: ApiPublicHooksReconcileTradesRoute,
  ApiPublicHooksReplayDlqRoute: ApiPublicHooksReplayDlqRoute,
  ApiPublicHooksReplayStatusRoute: ApiPublicHooksReplayStatusRoute,
  ApiPublicHooksScanRoute: ApiPublicHooksScanRoute,
  ApiPublicTelegramWebhookRoute: ApiPublicTelegramWebhookRoute,
  ApiPublicV1AnalysisRoute: ApiPublicV1AnalysisRoute,
  ApiPublicV1SignalsRoute: ApiPublicV1SignalsRouteWithChildren,
  ApiPublicV1WebhooksSubscribeRoute: ApiPublicV1WebhooksSubscribeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
